{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-main",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-main",
        "namespace": "monitoring",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/component": "alert-router",
          "app.kubernetes.io/instance": "main",
          "app.kubernetes.io/name": "alertmanager",
          "app.kubernetes.io/part-of": "kube-prometheus",
          "app.kubernetes.io/version": "0.23.0"
        }
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "alertmanager.yaml": "AgAStQODUx1t9XfmjsfImuGisFtrJUbEw1sTfxwBS89bPUkBMbPe8JGN/Lvmh8VkMZ3V0RhXQPtn3T/T2aJKjhWHGqdxm6g1UU40HR7kVdS/J4+nC4M4zUeMWcIVy6WjpAqVFp8Wu8/ofjwiFp+xG8HJsxwRUhCefIzbIVy/tXnsQevePoqt71b0YNmzACkjv5QSL22E64Q90LCeeWa79nxV1T5TpNYD+V54KipKbCWY3WWeiKZ/rg7goALdk2Oi70/KtMO9vjKmJSsu5lX9HAuYjzq32GNmqFcFVq4tEIhibORQsIMVuHSY5Y3qjY3GeTtfwvzXG+k2HB74mVZXMWz8nRtNwb1IZB5xK+Us79ZxWu39BE3+Ehs4hLY7Z+jfL1i7FUJo8ky5H4+hKs0I4BWsaFISnO4IEDK3D+9w3MATYOH1KjsxOOa0fKmLE8Kqfea6uKDkzgyf8gQEzIk/54HMZuJQF2Mjfs0E+LRsqDwjWNsHO/7FzvU5PftWpBChYGtdDNXusAhHWz7IFk0ymFVvHYZs9p2cBbANOeqVOHSIN80501uhI6ArBTxxDYIlX646iUVD1kGM1tD5kpQ7M0/jCvEuqzwv8OjwnZW6fzGq3owuOuAg2aWuBnOcJ2oaNfGp8T79FuN5ch9y9ecr8YpT+5wdPoidYTJ6kZvpX91jQ+3Gv9uGXu4iGaINcfHRuLpaw00cvaE1D/Yg5I+nmaIyT5R1vcWJaPuyJ7PMPONbsQ4BJPJGEboy0Sx5OLFsdIJqkA9WTt1hi5wIPWOmlpQHmqJgPTYw5usOd3ThNk5MRYzlzwdEjOAkmTZJ5G/fC9/DpBy3wddVilV6XnDpUhzy5O1858Sm+SZdqdizzmIi806c23nlsA2Mvv4MsD8pdPlm4B2Ib/b9M+oYxDajv2q74HHBhkNAjJyipZ9mr1Lc3zemlAvZQeIYy1HCg/MGM03e7jwsZvc71hzMvCFKwjjlREf6CA1g4kSe8myfsLbKV/ks/8S6n1sQy+9yNRcxKe7bixP9dW2422YVF2Ki8tmBbs2uSCsQH6CBJk861H3yVXqh9J9Aihd9Z0008L53mBFxuf2t+xrvnoxgkYkvWYUzemBjFYt5uL2mGQGVxPdw8OZTQrIIHz6f0vbKSPYCiNYpx3iBh5wxoEpvz2CCzNGia+6+i/qECPmrA1Fp15gHxdWXNc3IQ8F9BVPBjFOMxZcnrT8GrLWyzkcLeWnvKoqIeiFUlJetLOlzRn/VhV/VhlSiwWrNK+4Ml0xnX7oUkv5ZVnSlJsIUcwdpl7y7ttT1yyrDPfImBd+wOFXkdNYxWS65gUmJid8S0+rG+fQFEXd5Sx2NFvcEwszV6/174LuQB7b9yU7Kh2zAvpeAC5vO8OF/SUJ8E3HAA+8i3uZv4kcSNf4YsBPo+2ODRaOpBZboT7S7uwH5uKPBpfQkJXo5hhRkWa9FRy+9+/eMyt5Z4qJDttxtr+Wktf+Hwl1ktGc5D7eTbFR3kxZ6LQJK7aVNiKI/OzGgJN7XvKCZXvTvBQqhYQaAAVtQ+/knZk2Os1NNBFp5WW8E8ndgKefDm0hic44Kaa+AVIoc6A19zUyIggTlTM9tJqbv+Wr4nFDHNVQQP3IC7mdGXPDxnlXvdxwRpJc/xVhdciHz0mHd9ljL47EFpN2nDU0AIHNIkN40qvtR6BnONSfW8D0gh3DF5pxVRJIw064WqgVnBuPfV3Ocz+gGqHrXnmYUXtRH/f9zZr+X5/EJ9r/WvmusOIyQuWZxE99tpFAktvC3N3chvzeLECMshwr4XARDSD96bko/KEluNCYMxEkdc3IDKX2rLBK9SvFIGi3+qwBqCDIRSVO9BVzZKepItMU7zs7mMJj86hf40rScIsp0+ZOBzXBEnAiKVhXgPyiQnODwr4nmrh9vS77GalFTKDiPqQtJww4LJQHace+v08xTuPdHNcpYkmtS5nD52Mi/bWA+p1CA3RrHw0CfwABcQ0wHTakCouN8PVyIVBgpNTKAlkb+fKtREhJy2Gnfx+NzWDgGUgMLMm3PO2vDiUMtELzTLckvPDnEkYHPVlMFGYK5dTv5zVHZcpDGxYIl9D7EaIHALzxhTMhrfR1LzBSeWKE64LUvBJoD6pO15nKmukuBwGGEYGKKD+cO/yaawQGcvi6SDc8kHL9YmVtR0HTwTv1dm3w5hFUiqubfLxNujZI6ERAWdaA+dAbHd7r05hSoCa+ZPUqDESpdBQYWJp8nEQ8ZsBY/GS+j3A1KwKQEZEFyMPgUDAH1gbxRA022s6CUar4T4zpZGDT1DsZn"
    }
  }
}
