{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-main",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-main",
        "namespace": "monitoring",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/component": "alert-router",
          "app.kubernetes.io/instance": "main",
          "app.kubernetes.io/name": "alertmanager",
          "app.kubernetes.io/part-of": "kube-prometheus",
          "app.kubernetes.io/version": "0.23.0"
        }
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "alertmanager.yaml": "AgA1P0eGKhZr3l0BhWRwGfwIPm/vSNufkClraYHQP9VF3VsNytIXwLnDdvy3opbsyloCRaaSw0Jv3oiR5fegWQwYj2QBiBixDUinOWKdD71p9Jxdpo+T99C5Q/0s+/qa3iMW0A8KVuGV5HfP74VJYcbJbB1hbAk9jahjKepy4sB03XMLW7KN9nMzSzBUT1fKyXFwgWPEGzefaEwqKhTkO4kX/1oORKE58Z9Fq4kBG7eb0bzILw2RNAUEHPTheCSYcQUvj8yIi9VICoDnHqZ51BpbHiN/qnwXbPRxph6MfgMKq1gmC19fyTaEvk7Rg5lZqb5fRDdIOWC/pT0xVh+Q/bQYKMWEveCwGv1iud4d8DuKYL12mkzn4whYkb+uq5crgPNKtkE/wUipuT6P5SG/9Za0Y742qWvGpZ93RMkkhoIfCo8vPgsNA1iJPjAotDvZfAfm7o9wlEY8JxYeAfP14F2waLqEV6+4v7tH5d7KrrpPwpnwbPRzz1w39LFaTFZu0Z5lJHSM8vGaZR9AErN98jNVZcUE+LXb/da5wRmASih9zWzlBYj2b9alC/vC+C9ZtKyOfn9VC+vb9ebf5y1OydfJsqwI1UgPKVjkk14wgGiMYdPFIi+P4IkjI6pCX3NqoslEEPLr1prGL8TE8ESJtVFm4E7Rm3ezSgDP46w8xNwM4JWLg1ocN2TaIYnSNs4hCMXKb6w0jQxBzaXPYB2rBvufP9u0aNQLJQma8vJp97DTiJM5eeajCgQtz6lfvsHe4m9C9htHPn37bSWmCoytGDMLLi0eKpxt/wIlqnBBM/SCnXeIxI/1rm+srYNyoEUcxfJBriGAEaWdungAQiA72Lcl62IeqFJwFUoGhErwMFLGkZRAzNMMoz6DkydlOTRu+mItM4TKJxzv0uU68mqLalZHq7BgR4Hh42JGsUBsFdQOCKmfErsTAyCHymOWZGNpYRgV/L3WHiSztBHVmvvxf8O1lMg2fe68efWD4FnPOu3K+HFSMPe4xVpLDEw5+/zlRpzjxcmN3AQ7mXLSqUEn+3wNEK2FiC8FXFBWG2kvr434voOQFpr39vh93NNNvIQegSjy3aVePo+AA7CCod0qi0Mya2k1AYhWj9T/BoknTTEzwm85/eRhDNtQwIvtIdt7mwJTI+BQzY5Vh3K3HjSWsBpDkbB6UWg0NouZ5gcNQfvcKRDkXZtSjyYSxEn/7gw64jO3RV9+wN8Z/lt1sO9Lel268wTIUIpO7W/rvqloXwk8LkT+C24UFAzWK+peIOE7O5iWQ+NHpp/LcIHbwJCQ9I7Pl/vXSfLk2Ia/hf4bacPuRO7ovKkh/sQEHJ4UiuSGu0D0AjlphduCfwf+h/JgLhFkPabPp1KtKP3hITEMiwZtDJhMOETfrvSvjH42eZDtPydswqpfiGuIsDmsswYlMrW/nNofmwuT0MRHllMNpWg+/Pa5m3IxPguOVa7ORYDMSGmMzDo9fOpY1w2V4NQdoghfW3N1TONzbLKIHGxOToqaXSk2PWxfYWrVPyEf/qMHjZB88SJiHO2wWk48+fRMivN+F6LhwDzFG1caY2xRtT1uuxESIMLbHPBJq2E+oqe0xJljuwwiYaEp7lRsCweMl0J2eAHCbdYPWYgYdXtD+vVn8JhbaEzj4bsUyX3uBSmG0uppHnLQrh33xIYatoPH54f5j/BCRn29CB67QnBxl3+fbhtHP6Qpy6Pf3/BCktXKHtfz/16oq6w99LYrfyh8qV8d2mX0sNnpCf3XE/dY15ZmOngzml7aCWwW3XiURO/l6xB/FwjY9wbdrrd3iJrMB9TgAATqh8KpxHiIhr2AjWsPJ37TQ9fRVoTSO8kjMULo9vKt4S0t6mCxRlXVz634GSQxRbz3vWjE5xlX1AMpYRwZ0LPY6ifjqaPdCznxTZO2k30cEDznWbpeqV7QUQopHw9K/wEiBRi8bDOEl4sZyYYuT0H1gBB+wyzyiXZdmcUJ7rDVR7bRsVCXgdAT6qbh8M0xD0xpD5+renmd9OPy+agm3bump5pdJdCl2jZmKUWbpGDG5+8I3JvUqL9jrwDyA2zElyTkkv39xC/dQL5QCqGtpZFZBU05g7wLxaEiOtMOL+qSaqF+eN6DOdKiBvwVnInXmbbc9ZrCDSxi+UHuTbAq7W9smJJ72WrMDTBghx7CpBqUsFgYSMTVrpPtTzDkvU9ZDCmc/5O4XjUtY29Fd+9vtTfF+nkn+CvVQ+lfwYmpKC5SEdUUu17Ehnbx4qMqBQvwsTlkssd0x6ZV6JjRFyPuyD5StAYy7eG6nTRB4/RKJys7/fxvtIvbRBqYLknliDxOtW7Nvep21+BLdVVXN5C1eaIlxCSQwAkbx/7ZYJGmET3pcorZFd2xrmt0B4gPtm+yzJDFduxR3eAoXGFFQ1qEHWFHwwJI3OTnl2akqFgAS1t1mZ9ysHW8hdR46baHdU9cK+W6grkXolTM2c3V5Y8gyhRtcKJbnC25KST0rxQV3yRxl/HDA4jRHvBaI1KrGS+g01LxrJvs8WgkIDj7LmUKvUQKY5CZcnx6LbXUUyOPdgVC3NayioXaV16uamQRupQEsRiIKVTt22iUIYPLDCA54HlqeHMMXEcPDWDn8C0WbzvC3A13ztwafg=="
    }
  }
}
