{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-main",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-main",
        "namespace": "monitoring",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/component": "alert-router",
          "app.kubernetes.io/instance": "main",
          "app.kubernetes.io/name": "alertmanager",
          "app.kubernetes.io/part-of": "kube-prometheus",
          "app.kubernetes.io/version": "0.23.0"
        }
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "alertmanager.yaml": "AgBRohyh/UKwNJn4Tiz+82T4isvpP3rzm+2U+/rUu5OiAMbLY7z2WDztRObH4nFLcLSxvTbTpkGJ3F0mekbiMrux1KRfTXobO8bvyocGuouO6yuWHu4ZdlyOAddS9gABhfK5tKQPvvTwtoMODP8lhQAsKHRuTphruqDAICwzIslGw3WOgQ6FVBecwwYYVjwR8uv4wOAplpPbPQpY06/F2L+O/SIUdji0CcY/HYLguibHGYdLD/EVQkg6AHOhURwaHAiT5FtSeLch4i2bpRzoHmf+iMomrFEcC36U36KRqZKK+k7Q3WffQd9cE5WRLybYjTXqSiUmHx0fzSQK+sFm3ROzszMnvVruskzEiRaIAeanE5n7zvQ3eDcKdmVTlyWmK/3Eadi5p0dmKDNXXXOIfsjOdggg0k0ozt/VEOErA4u5cSKYSa4jQSqbjxwl0GC9ux1taNBH4/6+sSwdue1kSUJ/aLGIXgHUB0d+Up/yF0P2h5fquZGcIlGQF4ob8PlZNaiwE7rZjOJHM+dX/eC5JbXRr/fTg7Aczlbq8pg89YzidTKQEUytDerg9sNgTKJ/tendpuMNo/b8fVwqeUvGpEGbagNPPigIeOXnSopr2O2URWpd3CPBwfbse8hpe2I1k4ogwT0awe20YWBrk/fo6zs91K3P9L1sKcsANzLymS8yhdh2mr9Vf+8UdtUVrSIn4x1Zm087HLWNetdSTEYONB+9hfWoHnOtlIuwpyG4HuFoxc6JflYOhWaDWRb62vOMwGyru6X9FqdKL88l7gS4ub6pPknmkgtS9wTcisWSETgsWXW6ns08n1hGDyEzYjt0DNiDIL4+L8GTtllk5U3QVImkhhOKfpH7lStGnBJVzBBYd4WcRmwOD8xNU+7AT0/JeSwSj3JicZXNwcnoj4KD26774qUEZZmSXAsouMX/vNBAXY81c4Lq3BN4NdRi1+ZqGzqWQpLenYXAG7pNpeLcMaUNacPW6raqEcPGxSXmoIVz2Af4yWcpmMpJiU5Ocpa4DzsIBGCUqPX9XXCc2qx1tzqujZVN5j7OV0LLucIwMZAFDYw9DuGdlbA149EWDMtFZ9oIvbcV7pqrqCN8XGon+Ouw+CcV53FpVDAUN89HIkXG3FruaMUBIcFOuF9BSG2FVDyBiiYyObP6gHWqDJwZEeq2nAji0jJ7Nn3zjYga2BQjGYBga8lKYt+VA3SN8bkeAma/mo/ebU4qXmJXBcoiP4y5fVwbolwy58JanFNqiDvwqG0zaXrL9bP5s2u0rK5PGZTjwxujNzoih5SXX+8/5z6/DRXGcxE4hoWx4h4DV89vNbFBD1BKkOxgUDe+3CeD9M1o20x3PIPF6oPH9Egv0oqigcJ2kikR4MiKb9CXu/dtaZPYM01qUiqsoWkzVX+gkKtcjrB4UJtLd9EKDrXmLtO/gY0gXzgbThwEoDogvQyduBdF3OMYerqtTn0baW4LXZGz5shnf6WDoBn+A3AdYu+cj0DjU/qIahnu0kmHrWWWYvsnLWGzlKHN5M8/NSHYEksGopA56JuL05pqAFFSTswCtOwWvUVY31ADQILsckXdZBUBFxh3M1K3T8yaVakNB8mmirDcfd5PVbL1iGNCXvpWh64zhP9dRxHIT/ycjN+M/3xW28c0mC6f5iUh/ZgIMepANXklcAC6dMkhmC+wAbYZecWpq2eiIEZvLT9yc1P1UZfUgKNMl60h3ctLYkm/cinefhsWjLu0NfbKPho5zuRsH3Y1MWxTv2EwtE+V1HpFCXHZ7XbGDaJfZ0yZh7GjJNC0k/B8No/ACq6awYpYRfKYPK0REawUsXgRLmoBWbIqJuE0bATwQ5Pc33aQghCES1fhVkGpPKfbWC3sP2FIbsMjcDJUGbNN4JBWpWExc0hh3KScLMiz2KUrud5Rv+mpJyN7liAp5nHtEShIB5tctNf9bY4LIqAx+sJdS7kmyeYnOWfitUwnFFg7q9+c9DRmNyfhR8uJjNvUOHg8r9TpkOnfxd0VNqmviT1We4R3YJuV+fN4/0K1aQc6e8nYJ3jrSsOsnCfoI8a/SejGPd3S4Kaxkfs0hf7hBjRpRW4d8fI6bMQfJQEyQmSPivQR9shyrjcDmTf9OGhqRw1YKPf/X2X/0doWZgeEipfnZja6cwDCcqJJZeH4c6EMBzIwanmm4y6MZtX6xPhacnTLY9a02PmkrRyyXWRm/EjQphyqygA6w6KFxK8PbZFc9xTpBFV+CqxhxEEIiwDbXzs4QVv5IX5TpaBRHtN3gVWTam53h+zXGY98ScRd8aS96DzxGXZ6P6bapWlT0DoGmb6eb2S+1DlhYwbTSuTQBxUq4bEjGrxICSvdyWEX04vo5STKSDDqMTfBWZwYjGWrObhjyNSFEuL1GQLudIKbGSmh5icIn7ZE06BE3DBY+CZsPI9042MhXNE7ocGBqCd2/+1858J0VlRFyNuUQooR5lcgjZTqF0VeB/2fcYWZfOGAh/ys0Dj9OQIRmPisLcxQfNLy214q6U+4M4iMMlT3p/4PqdpZ+7oCHQL7o0tuRgr9PXb1BN5sTr4crrM3VKK07cX4GpbxjWYiWb0xlVVAEcLErSpHbOmeZzHf0Ad4sJ6p5LgX57hFnvcKMNoa+CSPrQ=="
    }
  }
}
